version: '3.8'

services:
  backend:
    build:
      context: ./users-portal  # adjust to your backend folder path
    container_name: backend
    ports:
      - "3000:3000"
    restart: always

  nginx:
    build:
      context: ./nginx  # folder where your Nginx Dockerfile + html + nginx.conf live
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
