version: '3.8'

services:
  db:
    container_name: kaamgar
    image: postgis/postgis:latest  # ✅ Switch to PostGIS image
    restart: always
    ports:
      - "2010:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_kaamgar:/var/lib/postgresql/data

  dbconsumer:
    container_name: kaamgar_consumers
    image: postgis/postgis:latest  # ✅ Switch to PostGIS image
    restart: always
    ports:
      - "2011:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_kaamgar_consumer:/var/lib/postgresql/data
  
  dbjobs:
    container_name: kaamgar_jobs
    image: postgis/postgis:latest  # ✅ Switch to PostGIS image
    restart: always
    ports:
      - "2012:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_kaamgar_jobs:/var/lib/postgresql/data

 
  # nginx:
  #   build:
  #     context: ./nginx
  #   container_name: nginx
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - backend

volumes:
  db_data_kaamgar:
  db_data_kaamgar_consumer:
  db_data_kaamgar_jobs:
